[package]
name = "halloween"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = {version = "0.8.0-alpha.9", git = "https://github.com/kuviman/geng"}